version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Jerusalem
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 5.0.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.1
    - 3.3.0
  - dependency-name: gatsby-remark-autolink-headers
    versions:
    - 4.0.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 3.3.0
  - dependency-name: gatsby
    versions:
    - 3.1.3
    - 3.3.1
  - dependency-name: framer-motion
    versions:
    - 3.10.5
    - 4.0.1
    - 4.1.7
    - 4.1.8
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.1.3
  - dependency-name: gatsby-transformer-remark
    versions:
    - 3.1.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.1.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.11.1
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.10.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
