import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Link } from "@/components/Link";
import NextLink from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "min-h-screen flex flex-col gap-12 items-center bg-zinc-900 text-zinc-200 pb-2"
        )}
      >
        <header className="flex justify-center items-center w-full py-6 border-b border-zinc-200">
          <h1 className="grow sm:max-w-3xl px-4 sm:px-8 text-3xl font-medium">
            <NextLink
              href="/"
              className="hover:text-emerald-500 focus-visible:text-emerald-500"
            >
              Dor Shinar
            </NextLink>
          </h1>
        </header>
        <main className="flex w-full flex-col items-center overflow-hidden">
          {children}
        </main>
        <footer className="flex items-center justify-center w-full">
          <span className="flex-1 sm:max-w-3xl px-4 sm:px-8">
            © {new Date().getFullYear()} Dor Shinar, built with{" "}
            <Link href="https://nextjs.org/">Next.js</Link>
          </span>
        </footer>
      </body>
    </html>
  );
}
